name: runner_test
on:
  workflow_dispatch: {}

jobs:
  test:
    runs-on: self-hosted
    defaults: { run: { shell: powershell } }
    steps:
      - run: Write-Host "Hello from $env:COMPUTERNAME"
      - run: python --version
